package com.thief.idea.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import com.thief.idea.PersistentState;
import com.thief.idea.util.HotkeyUtil;
import com.thief.idea.util.SettingUtil;

import javax.swing.*;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;

public class SettingUi {


    public JPanel mainPanel;
    public JLabel chooseFileLabel;
    public JLabel Label3;
    public JComboBox fontSize;
    public JComboBox fontType;
    public JLabel fontSizeLabel;
    public JLabel label6;
    public JComboBox lineCount;
    public JLabel label7;
    public JComboBox lineSpace;
    public JLabel label4;
    public JTextField before;
    public JLabel label5;
    public JTextField next;
    public JTextField bossKey;
    public JButton button2;
    public JTextField bookPathText;


    public SettingUi() {
        button2.addActionListener(e -> {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fileChooser.showOpenDialog(mainPanel);
            File file = fileChooser.getSelectedFile();
            if (file != null) {
                bookPathText.setText(file.getPath());
            }
        });
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();

        for (int i = 11; i < 25; i ++) {
            defaultComboBoxModel1.addElement(i + "");
        }

        fontSize.setModel(defaultComboBoxModel1);
        fontSize.setToolTipText("");
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement(PersistentState.DEFAULT_FONT);
        for (String font : SettingUtil.getAllFontType()) {
            defaultComboBoxModel2.addElement(font);
        }
        fontType.setModel(defaultComboBoxModel2);
        fontType.setToolTipText("");

        final DefaultComboBoxModel defaultComboBoxModel3 = new DefaultComboBoxModel();
        for (int i = 1; i < 11; i ++) {
            defaultComboBoxModel3.addElement(i + "");
        }
        lineCount.setModel(defaultComboBoxModel3);
        lineCount.setToolTipText("");

        final DefaultComboBoxModel defaultComboBoxModel4 = new DefaultComboBoxModel();
        for (int i = 0; i < 3; i ++) {
            defaultComboBoxModel4.addElement(i + "");
        }
        lineSpace.setModel(defaultComboBoxModel4);
        lineSpace.setToolTipText("");

        // 热键输入框：直接按下组合键即可录入，退格键清空
        installHotkeyCapture(before);
        installHotkeyCapture(next);
        installHotkeyCapture(bossKey);
    }

    /**
     * 热键输入框按键捕获：
     * 按下非修饰键时记录组合键并显示，退格键清空；
     * 捕获期间置位 HotkeyUtil.editingHotkey，避免误触发全局老板键
     **/
    private void installHotkeyCapture(JTextField field) {
        field.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                int keyCode = e.getKeyCode();
                // 单独按下修饰键或 Esc 时忽略
                if (keyCode == KeyEvent.VK_SHIFT || keyCode == KeyEvent.VK_CONTROL
                        || keyCode == KeyEvent.VK_ALT || keyCode == KeyEvent.VK_META
                        || keyCode == KeyEvent.VK_WINDOWS || keyCode == KeyEvent.VK_ESCAPE) {
                    return;
                }
                e.consume();
                if (keyCode == KeyEvent.VK_BACK_SPACE) {
                    field.setText("");
                    return;
                }
                field.setText(HotkeyUtil.format(keyCode, e.getModifiersEx()));
            }
        });
        field.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                HotkeyUtil.editingHotkey = true;
            }

            @Override
            public void focusLost(FocusEvent e) {
                HotkeyUtil.editingHotkey = false;
            }
        });
    }

    public void innit(PersistentState persistentState) {
        if (fontSize.getSelectedItem() == null) {
            fontSize.setSelectedItem(14);
        }
        bookPathText.setText(persistentState.getBookPathText());
        fontSize.setSelectedItem(persistentState.getFontSize());
        fontType.setSelectedItem(persistentState.getFontType());
        before.setText(persistentState.getBefore());
        next.setText(persistentState.getNext());
        lineCount.setSelectedItem(persistentState.getLineCount());
        lineSpace.setSelectedItem(persistentState.getLineSpace());
        bossKey.setText(persistentState.getBossKey());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:max(60dlu;d):noGrow,left:4dlu:noGrow,fill:180px:noGrow,left:6dlu:noGrow,fill:max(d;4px):noGrow", "top:4dlu:noGrow,center:d:noGrow,top:6dlu:noGrow,center:d:noGrow,top:6dlu:noGrow,center:d:noGrow,top:6dlu:noGrow,center:d:noGrow,top:6dlu:noGrow,center:d:noGrow,top:6dlu:noGrow,center:d:noGrow,top:6dlu:noGrow,center:d:noGrow,top:6dlu:noGrow,center:d:noGrow,top:6dlu:noGrow,center:d:noGrow"));
        chooseFileLabel = new JLabel();
        chooseFileLabel.setText("选择文件:");
        CellConstraints cc = new CellConstraints();
        mainPanel.add(chooseFileLabel, cc.xy(2, 2));
        bookPathText = new JTextField();
        mainPanel.add(bookPathText, cc.xy(4, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        button2 = new JButton();
        button2.setText("...");
        mainPanel.add(button2, cc.xy(6, 2));
        Label3 = new JLabel();
        Label3.setText("字号:");
        mainPanel.add(Label3, cc.xy(2, 4));
        fontSize = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("8");
        defaultComboBoxModel1.addElement("9");
        defaultComboBoxModel1.addElement("10");
        defaultComboBoxModel1.addElement("11");
        defaultComboBoxModel1.addElement("12");
        defaultComboBoxModel1.addElement("13");
        defaultComboBoxModel1.addElement("14");
        defaultComboBoxModel1.addElement("15");
        defaultComboBoxModel1.addElement("16");
        defaultComboBoxModel1.addElement("17");
        defaultComboBoxModel1.addElement("18");
        defaultComboBoxModel1.addElement("19");
        defaultComboBoxModel1.addElement("20");
        defaultComboBoxModel1.addElement("21");
        defaultComboBoxModel1.addElement("22");
        defaultComboBoxModel1.addElement("23");
        defaultComboBoxModel1.addElement("24");
        fontSize.setModel(defaultComboBoxModel1);
        fontSize.setToolTipText("");
        mainPanel.add(fontSize, cc.xy(4, 4, CellConstraints.FILL, CellConstraints.DEFAULT));
        fontSizeLabel = new JLabel();
        fontSizeLabel.setText("字体:");
        mainPanel.add(fontSizeLabel, cc.xy(2, 6));
        fontType = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        fontType.setModel(defaultComboBoxModel2);
        fontType.setToolTipText("");
        mainPanel.add(fontType, cc.xy(4, 6, CellConstraints.FILL, CellConstraints.DEFAULT));
        label6 = new JLabel();
        label6.setText("每行页数:");
        mainPanel.add(label6, cc.xy(2, 8));
        lineCount = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel3 = new DefaultComboBoxModel();
        defaultComboBoxModel3.addElement("1");
        defaultComboBoxModel3.addElement("2");
        defaultComboBoxModel3.addElement("3");
        lineCount.setModel(defaultComboBoxModel3);
        lineCount.setToolTipText("");
        mainPanel.add(lineCount, cc.xy(4, 8, CellConstraints.FILL, CellConstraints.DEFAULT));
        label7 = new JLabel();
        label7.setText("行距:");
        mainPanel.add(label7, cc.xy(2, 10));
        lineSpace = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel4 = new DefaultComboBoxModel();
        defaultComboBoxModel4.addElement("0");
        defaultComboBoxModel4.addElement("1");
        defaultComboBoxModel4.addElement("2");
        lineSpace.setModel(defaultComboBoxModel4);
        lineSpace.setToolTipText("");
        mainPanel.add(lineSpace, cc.xy(4, 10, CellConstraints.FILL, CellConstraints.DEFAULT));
        label4 = new JLabel();
        label4.setText("上一页热键:");
        mainPanel.add(label4, cc.xy(2, 12));
        before = new JTextField();
        before.setToolTipText("点击后直接按下组合键即可修改，退格键清空");
        mainPanel.add(before, cc.xy(4, 12, CellConstraints.FILL, CellConstraints.DEFAULT));
        label5 = new JLabel();
        label5.setText("下一页热键:");
        mainPanel.add(label5, cc.xy(2, 14));
        next = new JTextField();
        next.setToolTipText("点击后直接按下组合键即可修改，退格键清空");
        mainPanel.add(next, cc.xy(4, 14, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label8 = new JLabel();
        label8.setText("老板键:");
        mainPanel.add(label8, cc.xy(2, 16));
        bossKey = new JTextField();
        bossKey.setToolTipText("点击后直接按下组合键即可修改，退格键清空");
        mainPanel.add(bossKey, cc.xy(4, 16, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label9 = new JLabel();
        label9.setText("提示：点击热键输入框后直接按下组合键即可修改，退格键清空；设置完成后点击工具窗口的刷新按钮生效");
        mainPanel.add(label9, cc.xyw(2, 18, 5));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
